version: '3.8'

services:
  auth-service:
    working_dir: /src/app/server
    container_name: ${APP_NAME}
    ports: 
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - ./:/src/app/server
    build: ./
    networks:
      - socket-project
  redis-service: 
    image: redis:latest 
    container_name: ${REDIS_HOST}
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    networks:
      - socket-project

networks:
  socket-project:
    external: true
    driver: bridge
